### ISSUE TITLE
Error: iCloud Passwords failed to response in time

### ISSUE THREAD

**Issue by Lakori4** [au2001/icloud-passwords-firefox#17]
Anyone knows how to solve it?

**Comment by au2001** [comment]
Hi, which operating system are you using and which version do you have?
Only macOS Sonoma (14.0) is supported right now

**Comment by Lakori4** [comment]
ahhhhh, my bad, thought it was for windows

**Comment by Lakori4** [comment]
I'm running firefox for Windows and iCloud keychain doesn't have an extension for Firefox. 

I'm assuming it doesn't support Windows.

**Comment by au2001** [comment]
Windows support is planned but not a priority to be honest
Progress will be tracked in #18

**Comment by Lakori4** [comment]
I'll be looking for it when it's launched, but ofc dont rush it, there is no need. 

PD: keep the good work!
