### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by au2001** [au2001/icloud-passwords-firefox#18]
This extension could support Firefox running on Windows by using the [iCloud for Windows](https://support.apple.com/kb/DL1455) app.

**Comment by aurelien-garnier** [comment]
The native messaging host seems not to be enabled on Windows by default, it probably requires a script such as this one:\
https://github.com/ArakawaHenri/Grant_Privileges_for_iCloudPasswords/blob/master/grant_privileges/grant_privileges.cpp
