### ISSUE TITLE
Availability in Firefox extension directory

### ISSUE THREAD

**Issue by hacketiwack** [au2001/icloud-passwords-firefox#30]
I think this extension is a real benefit for the end user of Firefox on macOS.
Therefore, I wanted to install it but couldn't find it anymore in the official [Firefox extension directory](https://addons.mozilla.org/en-US/firefox/extensions/).
Is there something that could be done to publish the extension automatically from GitHub to the Firefox official website?

**Comment by hacketiwack** [comment]
Amazing! Thanks. I unfortunately don't have anymore access to Apple support to fast forward the process on Apple side.

**Comment by UsernamesLame** [comment]
Is it possible to just rename it?

**Comment by au2001** [comment]
@UsernamesLame Unfortunately not, the exact extension ID `password-manager-firefox-extension@apple.com` is needed for it to work correctly.

**Comment by UsernamesLame** [comment]
> @UsernamesLame Unfortunately not, the issue is presumably regarding the code itself. I've rewritten all of it in version 1.1.0, hoping it can be reinstated. The extension cannot be republished in the mean time under a different name as the exact extension ID `password-manager-firefox-extension@apple.com` is required for it to work properly.

Is there any specific reason for ```password-manager-firefox-extension@apple.com```?

**Comment by au2001** [comment]
> But to understand correctly,
> 
> https://github.com/au2001/icloud-passwords-firefox/blob/433ff9c1190b60325cd39a0df7352d9accbf850d/src/api.ts
> 
> `chrome.runtime.connectNative("com.apple.passwordmanager")).`
> 
> You're connecting to a _I assume_ unix socket?

Correct, that's a [native messaging port](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging).
Here is its [manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) as installed by macOS Sonoma as of 14.2.1:
`/Library/Application Support/Mozilla/NativeMessagingHosts/com.apple.passwordmanager.json`
```json
{
    "name": "com.apple.passwordmanager",
    "description": "PasswordManagerBrowserExtensionHelper",
    "path": "/System/Cryptexes/App/System/Library/CoreServices/PasswordManagerBrowserExtensionHelper.app/Contents/MacOS/PasswordManagerBrowserExtensionHelper",
    "type": "stdio",
    "allowed_extensions": [
        "password-manager-firefox-extension@apple.com"
    ]
}
```

> Are you just trying to ensure you don't break it for people who used to have it installed? I would just break the old installs to restore it and not get DMCAd.

Because of the `allowed_extensions` above, the extension would not work at all if it was republished as-is.\
It would require an install script ran on macOS (e.g. in the Terminal) to add the new extension ID to this manifest.

**Comment by au2001** [comment]
The extension has been restored on [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/icloud-passwords/) as of today.
GitHub Actions implementation will be tracked separately in #31.

**Comment by 4faramita** [comment]
If you are here to see how to enable iCloud Passwords for librewolf:

```sh
echo '{
    "name": "com.apple.passwordmanager",
    "description": "PasswordManagerBrowserExtensionHelper",
    "path": "/System/Cryptexes/App/System/Library/CoreServices/PasswordManagerBrowserExtensionHelper.app/Contents/MacOS/PasswordManagerBrowserExtensionHelper",
    "type": "stdio",
    "allowed_extensions": [
        "password-manager-firefox-extension@apple.com"
    ]
}' > ~/Library/Application\ Support/librewolf/NativeMessagingHosts/com.apple.passwordmanager.json
```
