### ISSUE TITLE
Passkey support

### ISSUE THREAD

**Issue by au2001** [au2001/icloud-passwords-firefox#9]
iCloud Keychain supports generating and saving passkeys.
A new tab for passkeys could be added with the ones available for the current site and the ability to create a new one.

**Comment by MStankiewiczOfficial** [comment]
This feature is no longer needed in the extension because Firefox since version 228 supports Passkeys from iCloud

**Comment by au2001** [comment]
@MStankiewiczOfficial Do you have a link to the release notes describing this feature?
I don't see anything in version 128 (July 9, 2024), and version 228 is still far out

**Comment by MStankiewiczOfficial** [comment]
Of course, I was referring to version 128. Unfortunately, I can't find it, while I use this version of the browser on my Mac and use iCloud Passkeys in it on a daily basis

**Comment by au2001** [comment]
Just tested, it must have been implemented in an earlier version but it does work fine natively. I'll close this issue, thanks!
